### ISSUE TITLE
[BUG] Local Favorite

### ISSUE THREAD

**Issue by IamLupo** [yobson1/FavCat-Restored#3]
When i try to add  a world to "Local favorite" it doesn't get displayed in that group. It looks like the world is added in the background but just not displayed.
I notice this issue doesnt happen to all worlds.

These worlds doesn't work as example:
https://en.vrcw.net/world/detail/wrld_58e5a8a7-100f-4346-85e1-a6e00d871c61
https://en.vrcw.net/world/detail/wrld_da1b9df3-f10f-43e4-9fe8-42adda87d159

### **Screenshots**
You see i added to world to "Local Favorite"
![Picture 1](https://user-images.githubusercontent.com/8842375/172376554-1c8863ac-fb45-4a25-867d-958b2ee2a711.png)

You see here the world is not in the list:
![Picture 2](https://user-images.githubusercontent.com/8842375/172376544-4c76343a-f2c9-47c1-8485-f2f26026f33e.png)

### **Questions:**
 - Which version of VRChat are you running?
Unity Version: 2019.4.31f1
Game Version: 2022.2.1p4-1205--Release

 - Are you using the latest version of FavCatRestored?:
 Yes, 1.1.18

 - Are you using the latest version of UIX?:
 I don't know
 
 - Does the issue happen if you only use FavCatRestored & UIX?
 I dont know

 - Are you using the latest version of melonloader / emmVRC?:
Yes

Here my Melonloader log:
[Latest.log](https://github.com/yobson1/FavCat-Restored/files/8853052/Latest.log)

**Comment by HeyImRuu** [comment]
Hi the new method appears to not include ApiAvatar responses, and now this bug affects avatars rather than worlds

**Comment by yobson1** [comment]
> Hi the new method appears to not include ApiAvatar responses, and now this bug affects avatars rather than worlds

I'm not able to replicate either, if you continue to have issues please create a new issue with some more details of what's going wrong. Include any errors/melon loader log if applicable.
